env:
  matrix:
    - ELM_VERSION=0.18.0

cache:
  directories:
    - examples/design-system/elm-stuff
    - examples/music-player/elm-stuff
    - examples/music-player/explorer/elm-stuff
    - examples/simple/elm-stuff
    - node_modules
    - sysconfcpus

language: node_js

node_js:
  - "6"
  - "8"
  - "node"

install:
  - | # build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - npm install elm@$ELM_VERSION

script:
  - cd $TRAVIS_BUILD_DIR/examples/button/ && $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 ../../node_modules/.bin/elm make Main.elm
  - cd $TRAVIS_BUILD_DIR/examples/button/ && $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 ../../node_modules/.bin/elm make Explorer.elm
  - cd $TRAVIS_BUILD_DIR/examples/button/ && $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 ../../node_modules/.bin/elm make ExplorerWithNotes.elm
  - cd $TRAVIS_BUILD_DIR/examples/dsm/ && $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 ../../node_modules/.bin/elm make src/Main.elm
