name: build, lint and analyse

on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1.1.0

    - name: Setup cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install deps
      run: |
        npm install

    - name: Run elm
      run: |
        ./node_modules/.bin/elm make src/elm/UIExplorer.elm --output /dev/null

    - name: Elm-analyse it
      run: |
        ./node_modules/.bin/elm-analyse


